EnglishDictionaryWeb/Controllers/LearnedController.cs
using EnglishDictionaryWeb.Data;
using EnglishDictionaryWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EnglishDictionaryWeb.Controllers
{
    [Authorize]
    public class LearnedController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public LearnedController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        

        

        // Öğrenilen Kelimeler (Level = 0)
        public async Task<IActionResult> LearnedList()
        {
            var user = await _userManager.GetUserAsync(User);

            var learnedWords = await _context.Words
                .Where(w => w.AppUserId == user.Id && w.Level == 0)
                .ToListAsync();

            return View(learnedWords);
        }
    }
}

EnglishDictionaryWeb/Controllers/PracticeController.cs
using EnglishDictionaryWeb.Data;
using EnglishDictionaryWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EnglishDictionaryWeb.Controllers
{
    [Authorize]
    public class PracticeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public PracticeController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // Filter ve sıralama için parametre olarak sortOrder alıyoruz
        public async Task<IActionResult> PracticeList(string sortOrder)
        {
            var user = await _userManager.GetUserAsync(User);

            // Sadece Level > 0 olan kelimeleri çekiyoruz (öğrenilmemiş veya pratik yapılacaklar)
            var wordsQuery = _context.Words
                .Where(w => w.AppUserId == user.Id && w.Level > 0);

            // Sıralama seçeneğine göre sıralama yap
            switch (sortOrder)
            {
                case "level_desc":
                    wordsQuery = wordsQuery.OrderByDescending(w => w.Level);
                    break;
                case "level_asc":
                    wordsQuery = wordsQuery.OrderBy(w => w.Level);
                    break;
                case "text_asc":
                    wordsQuery = wordsQuery.OrderBy(w => w.Text);
                    break;
                case "text_desc":
                    wordsQuery = wordsQuery.OrderByDescending(w => w.Text);
                    break;
                default:
                    wordsQuery = wordsQuery.OrderBy(w => w.Text);
                    break;
            }

            var words = await wordsQuery.ToListAsync();

            ViewData["CurrentSort"] = sortOrder;
            TempData["CurrentSort"] = sortOrder;

            return View(words);
        }
        [HttpPost]
        public async Task<IActionResult> IncreaseLevel(int id)
        {
            var word = await _context.Words.FindAsync(id);
            if (word != null && word.AppUserId == _userManager.GetUserId(User) && word.Level < 7)
            {
                word.Level++;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("PracticeList", new { sortOrder = TempData["CurrentSort"] });
        }

        [HttpPost]
        public async Task<IActionResult> DecreaseLevel(int id)
        {
            var word = await _context.Words.FindAsync(id);
            if (word != null && word.AppUserId == _userManager.GetUserId(User) && word.Level > 1)
            {
                word.Level--;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("PracticeList", new { sortOrder = TempData["CurrentSort"] });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var word = await _context.Words.FindAsync(id);
            if (word != null && word.AppUserId == _userManager.GetUserId(User))
            {
                _context.Words.Remove(word);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("PracticeList");
        }

    }
}

EnglishDictionaryWeb/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;

namespace EnglishDictionaryWeb.Controllers
{
    public class QuizController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EnglishDictionaryWeb/Controllers/WordController.cs
using EnglishDictionaryWeb.Data;
using EnglishDictionaryWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EnglishDictionaryWeb.Controllers
{
    [Authorize] // Sadece giriş yapan kullanıcılar erişebilir
    public class WordController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public WordController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var words = await _context.Words
                .Where(w => w.AppUserId == user.Id)
                .ToListAsync();

            return View(words);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(string text, string translation)
        {
            var user = await _userManager.GetUserAsync(User);

            var word = new Word
            {
                Text = text,
                Translation = translation,
                AppUserId = user.Id
            };

            _context.Words.Add(word);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

EnglishDictionaryWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - English Dictionary</title>

    <!-- CSS -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @* Sidebar buraya eklenecek *@
        @await Html.PartialAsync("_Sidebar")
        
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            
            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                @* Topbar buraya eklenecek *@
                @await Html.PartialAsync("_Topbar")


                <!-- Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>

            </div>
        </div>
    </div>

    <!-- JS -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/js/sb-admin-2.min.js"></script>
</body>
</html>

EnglishDictionaryWeb/Views/Shared/_Sidebar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-text mx-3">English Dictionary</div>
    </a>

    <hr class="sidebar-divider my-0" />

    <li class="nav-item">
        <a class="nav-link" asp-controller="Home" asp-action="Index">
            <i class="fas fa-home"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-controller="Word" asp-action="Index">
            <i class="fas fa-book"></i>
            <span>My Words</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-controller="Quiz" asp-action="Index">
            <i class="fas fa-question"></i>
            <span>Quiz</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-controller="Learned" asp-action="LearnedList">
            <i class="fas fa-check-circle"></i>
            <span>Learned Words</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-controller="Practice" asp-action="PracticeList">
            <i class="fas fa-book-reader"></i>
            <span>Practice List</span>
        </a>
    </li>

    <hr class="sidebar-divider" />

    <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-action="Logout">
            <i class="fas fa-sign-out-alt"></i>
            <span>Logout</span>
        </a>
    </li>

</ul>
<!-- End of Sidebar -->

EnglishDictionaryWeb/Views/Shared/_Topbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Kullanıcı menüsü, çıkış vb. -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                <img class="img-profile rounded-circle" src="~/img/undraw_profile.svg" />
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" asp-controller="Account" asp-action="Logout">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>

</nav>